=== IFT8/study-java/study_java/sp_xml/src/main/resources/schema/02.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.assupg.cn/XMLSchema/02"
        elementFormDefault="qualified">
    <!--complexType
            all 没有顺序
            sequence 有顺序
            choice 在其中选择一个
        -->
    <element name="books">
        <complexType>
            <!--maxOccurs 表示最大出现浆糊-->
            <sequence maxOccurs="unbounded">
                <element name="book">
                    <complexType>
                        <sequence minOccurs="1" maxOccurs="unbounded">
                            <element name="title" type="string"/>
                            <element name="content" type="string"/>
                            <choice>
                                <element name="author" type="string"/>
                                <element name="authors">
                                    <complexType>
                                        <all> <!--每个元素只能出现一次-->
                                            <element name="author" type="string"/>
                                        </all>
                                    </complexType>
                                </element>
                            </choice>
                        </sequence>

                        <!--属性的定义，属性必须在sequence 之后进行定义-->
                        <attribute name="id" type="int" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== IFT8/study-java/study_java/sp_java_Xml/src/main/resources/schema/02_1.xml
<?xml version="1.0" encoding="utf-8" ?>
<book:books xmlns:book="http://www.assupg.cn/XMLSchema/02"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.assupg.cn/XMLSchema/02 02.xsd">
    <book:book id="1">
        <book:title>Java in action</book:title>
        <book:content>Java is good</book:content>
        <book:author>Bruce</book:author>
    </book:book>
    <book:book id="2">
        <book:title>SOA in action</book:title>
        <book:content>soa in difficult</book:content>
        <book:authors>
            <book:author>Jike</book:author>
        </book:authors>
    </book:book>
</book:books>
